'use client'

import React from 'react'
import { CaseStudyTemplate, CaseStudyData } from '@/components/case-study-template'

const SOLAE_DATA: CaseStudyData = {
  campaignId: 'solae',
  caseNumber: '01',
  name: 'SOLAÉ',
  tagline: 'Feels like water. Shields like SPF50+.',
  skuFocus: 'AIRVEIL Invisible Sun Serum · 50ml (SPF50+ PA++++)',
  deliverablesCount: '29 Master Production Assets',
  channelsText: 'Meta · Instagram · Editorial',
  heroImage: '/images/solae/editorial/solae-photo-01.jpg',
  heroCaption: 'Frosted ivory bottle with sculptural swirl crest and champagne-gold pump.',
  heroBadge: 'Flagship Spec Commercial 01 · Witlyn Standard',
  brief: {
    whatItIs:
      'A 50ml daily facial sunscreen and hydrating serum hybrid (SPF50+ PA++++) delivering broad-spectrum UVA and UVB defense. It operates simultaneously as a high-level photoprotective shield, a deeply hydrating daily serum, and a lightweight gripping primer under foundation.',
    whyItExists:
      'Up to 90% of consumers avoid or skip daily sunscreen because traditional formulas leave a chalky white cast, feel heavy and greasy in humid climates, clog pores, sting delicate eyes, and cause foundation to pill. SOLAÉ exists to eliminate every sensory and aesthetic friction point of daily sun protection.',
    whyDifferent: [
      {
        title: '100% Clear Water-Veil Texture',
        desc: 'Dispenses as a crystal-clear, ultra-fluid water-serum rather than a heavy white lotion, absorbing in 3 seconds with zero white cast on any skin tone.',
      },
      {
        title: 'Air-Light & Makeup-Friendly',
        desc: 'Engineered specifically for hot, humid climates to dry down to an imperceptible, non-greasy satin finish that grips makeup without pilling or midday sebum breakthrough.',
      },
    ],
    targetAudience:
      'Daily makeup wearers, urban commuters living in warm or humid climates prone to sweat and shine, and prestige skincare buyers demanding high UV protection without pore congestion.',
    packagingSpecs: {
      container:
        'Slim 50ml frosted cylindrical bottle in soft ivory-cream finish, featuring a 3D sculptural embossed petal swirl crest with a brushed champagne-gold pump.',
      labelTypography:
        'SOLAÉ (clean serif with acute accent) | AIRVEIL | SPF50+ PA++++ | Invisible Sun Serum | 50ml',
    },
    marketAngles: [
      {
        title: 'Anti-White Cast Reality',
        desc: '"Sunscreen shouldn\'t look like white paint" — direct-response visual proof showing instantaneous clear absorption on dark and melanin-rich skin.',
      },
      {
        title: 'Cosmetic Compatibility Hook',
        desc: '"If your SPF pills under foundation, you\'re wearing the wrong formula" — establishing SOLAÉ as the ultimate weightless priming step.',
      },
    ],
  },
  strategy: {
    hooks: [
      {
        id: 1,
        angle: 'Sensory Friction Angle (Anti-White Paint)',
        channelFit: 'Meta 4:5 Feed & Instagram Reels',
        quote: "Sunscreen shouldn't look like white paint.",
        rationale:
          'Visually confronts the universal frustration of chalky mineral casts by opening with a side-by-side comparison of opaque white cream versus SOLAÉ crystal-clear water veil.',
      },
      {
        id: 2,
        angle: 'Sensory Viscosity & Speed Hook',
        channelFit: 'Instagram Stories & Meta Feed Stills',
        quote: 'Feels like water. Shields like SPF50+.',
        rationale:
          'Highlights the high-spreadability micro-fluid texture that absorbs in under three seconds, proving high protection does not require thick greasy occlusives.',
      },
      {
        id: 3,
        angle: 'Foundation Pilling Contrarian Truth',
        channelFit: 'Paid Social Video & Carousels',
        quote: "If your SPF pills under foundation, you're wearing the wrong formula.",
        rationale:
          'Calls out the friction caused when skincare actives ball up under makeup, positioning AIRVEIL as an invisible cosmetic grip layer.',
      },
    ],
  },
  tabs: [
    { id: 'all', label: 'All Assets' },
    { id: 'editorial', label: 'Editorial Stills' },
    { id: 'meta', label: 'Meta Ads' },
    { id: 'instagram', label: 'Instagram Suite' },
  ],
  prevLink: {
    href: '/work/vyraa',
    label: '05 VYRAA Neck Complex',
  },
  nextLink: {
    href: '/work/lipea',
    label: '02 LIPÉA Lip Serum',
  },
  assets: [
    // Editorial Stills (10)
    {
      id: 'solae-ed-01',
      title: 'Ivory Bottle Studio Capture',
      platform: 'editorial',
      type: 'image',
      src: '/images/solae/editorial/solae-photo-01.jpg',
      formatLabel: 'Editorial Still · 4:5',
      aspectRatio: 'aspect-[4/5]',
      caption: 'Frosted ivory bottle positioned under soft directional morning light.',
    },
    {
      id: 'solae-ed-02',
      title: 'Water Droplet Texture Study',
      platform: 'editorial',
      type: 'image',
      src: '/images/solae/editorial/solae-photo-02.jpg',
      formatLabel: 'Macro Still · 4:5',
      aspectRatio: 'aspect-[4/5]',
      caption: 'Macro surface capture highlighting the crystal-clear water droplet viscosity.',
    },
    {
      id: 'solae-ed-03',
      title: 'Sculptural Swirl Emboss',
      platform: 'editorial',
      type: 'image',
      src: '/images/solae/editorial/solae-photo-03.jpg',
      formatLabel: 'Packaging Detail · 4:5',
      aspectRatio: 'aspect-[4/5]',
      caption: 'Close-up of the tactile petal crest embossed on the frosted ivory glass.',
    },
    {
      id: 'solae-ed-04',
      title: 'Champagne-Gold Pump Detail',
      platform: 'editorial',
      type: 'image',
      src: '/images/solae/editorial/solae-photo-04.jpg',
      formatLabel: 'Hardware Still · 4:5',
      aspectRatio: 'aspect-[4/5]',
      caption: 'Brushed metallic champagne-gold pump engineered for clean dosage control.',
    },
    {
      id: 'solae-ed-05',
      title: 'Atmospheric Refraction Still',
      platform: 'editorial',
      type: 'image',
      src: '/images/solae/editorial/solae-photo-05.jpg',
      formatLabel: 'Editorial Still · 4:5',
      aspectRatio: 'aspect-[4/5]',
      caption: 'Direct sunlight caustic reflections casting warmth behind the sun serum bottle.',
    },
    {
      id: 'solae-ed-06',
      title: 'Formula Spatula Spread',
      platform: 'editorial',
      type: 'image',
      src: '/images/solae/editorial/solae-photo-06.jpg',
      formatLabel: 'Texture Still · 4:5',
      aspectRatio: 'aspect-[4/5]',
      caption: 'Ultra-thin water film spreading effortlessly across a cold acrylic plate.',
    },
    {
      id: 'solae-ed-07',
      title: 'Skin Melting Interaction',
      platform: 'editorial',
      type: 'image',
      src: '/images/solae/editorial/solae-photo-07.jpg',
      formatLabel: 'In-Use Still · 4:5',
      aspectRatio: 'aspect-[4/5]',
      caption: 'Liquid water serum absorbing immediately into skin upon light fingertip contact.',
    },
    {
      id: 'solae-ed-08',
      title: 'Hydration Dew Finish',
      platform: 'editorial',
      type: 'image',
      src: '/images/solae/editorial/solae-photo-08.jpg',
      formatLabel: 'Skin Finish · 4:5',
      aspectRatio: 'aspect-[4/5]',
      caption: 'Subtle hydrated sheen remaining on skin with zero white film or oily shine.',
    },
    {
      id: 'solae-ed-09',
      title: 'Architectural Pedestal Display',
      platform: 'editorial',
      type: 'image',
      src: '/images/solae/editorial/solae-photo-09.jpg',
      formatLabel: 'Studio Still · 4:5',
      aspectRatio: 'aspect-[4/5]',
      caption: 'Minimalist travertine podium framing the product against an airy warm background.',
    },
    {
      id: 'solae-ed-10',
      title: 'Sunlight Flare Silhouette',
      platform: 'editorial',
      type: 'image',
      src: '/images/solae/editorial/solae-photo-10.jpg',
      formatLabel: 'Mood Still · 4:5',
      aspectRatio: 'aspect-[4/5]',
      caption: 'Golden optical lens flare accentuating the lightweight protective concept.',
    },

    // Meta Ads Stills & Videos (9)
    {
      id: 'solae-meta-s01',
      title: 'Meta Core Feed Still',
      platform: 'meta',
      type: 'image',
      src: '/images/solae/meta/meta-still-01.jpg',
      formatLabel: '1:1 Square Feed',
      aspectRatio: 'aspect-square',
      caption: 'Direct-response hero composition formatted specifically for Meta square feeds.',
    },
    {
      id: 'solae-meta-s01sep',
      title: 'Meta Variant Feed Still',
      platform: 'meta',
      type: 'image',
      src: '/images/solae/meta/meta-still-01-sep.jpg',
      formatLabel: '1:1 Square Feed',
      aspectRatio: 'aspect-square',
      caption: 'Alternate product perspective highlighting clean packaging typography.',
    },
    {
      id: 'solae-meta-s02',
      title: 'Meta Zero Cast Comparison',
      platform: 'meta',
      type: 'image',
      src: '/images/solae/meta/meta-still-02.jpg',
      formatLabel: '4:5 Feed Portrait',
      aspectRatio: 'aspect-[4/5]',
      caption: 'Visual demonstration showing invisible sun defense on deeper skin tones.',
    },
    {
      id: 'solae-meta-s03',
      title: 'Meta Sensory Water Splash',
      platform: 'meta',
      type: 'image',
      src: '/images/solae/meta/meta-still-03.jpg',
      formatLabel: '4:5 Feed Portrait',
      aspectRatio: 'aspect-[4/5]',
      caption: 'Dynamic water splash surrounding the bottle to convey deep hydration.',
    },
    {
      id: 'solae-meta-s04',
      title: 'Meta Daily Commuter Angle',
      platform: 'meta',
      type: 'image',
      src: '/images/solae/meta/meta-still-04.jpg',
      formatLabel: '4:5 Feed Portrait',
      aspectRatio: 'aspect-[4/5]',
      caption: 'Clean lifestyle framing emphasizing effortless reapplication throughout the day.',
    },
    {
      id: 'solae-meta-v01',
      title: 'Meta Motion Reel: 3-Second Melt',
      platform: 'meta',
      type: 'video',
      src: '/images/solae/meta/meta-video-01.mp4',
      formatLabel: '9:16 Vertical Video',
      aspectRatio: 'aspect-[9/16]',
      caption: 'Rapid three-second skin absorption test captured in high-definition video.',
    },
    {
      id: 'solae-meta-v02',
      title: 'Meta Motion Reel: Water Drop Velocity',
      platform: 'meta',
      type: 'video',
      src: '/images/solae/meta/meta-video-02.mp4',
      formatLabel: '9:16 Vertical Video',
      aspectRatio: 'aspect-[9/16]',
      caption: 'Kinetic drop dispense highlighting the lightweight serum viscosity.',
    },
    {
      id: 'solae-meta-v03',
      title: 'Meta Motion Reel: Foundation Grip',
      platform: 'meta',
      type: 'video',
      src: '/images/solae/meta/meta-video-03.mp4',
      formatLabel: '9:16 Vertical Video',
      aspectRatio: 'aspect-[9/16]',
      caption: 'Smooth foundation glide over AIRVEIL showing zero pilling or patchiness.',
    },
    {
      id: 'solae-meta-v04',
      title: 'Meta Motion Reel: Solar Defense Test',
      platform: 'meta',
      type: 'video',
      src: '/images/solae/meta/meta-video-04.mp4',
      formatLabel: '9:16 Vertical Video',
      aspectRatio: 'aspect-[9/16]',
      caption: 'Micro-droplet dispersion visually proving broad-spectrum photoprotection.',
    },

    // Instagram Suite Stills, Story & Videos (10)
    {
      id: 'solae-ig-s01',
      title: 'Instagram Aesthetic Still 01',
      platform: 'instagram',
      type: 'image',
      src: '/images/solae/instagram/instagram-still-01.jpg',
      formatLabel: '4:5 Feed Portrait',
      aspectRatio: 'aspect-[4/5]',
      caption: 'Architectural composition styled with ivory stone for organic engagement.',
    },
    {
      id: 'solae-ig-s01sep',
      title: 'Instagram Detail Capture',
      platform: 'instagram',
      type: 'image',
      src: '/images/solae/instagram/instagram-still-01-sep.jpg',
      formatLabel: '4:5 Feed Portrait',
      aspectRatio: 'aspect-[4/5]',
      caption: 'High-contrast angled lighting revealing the precision embossed petal crest.',
    },
    {
      id: 'solae-ig-s02',
      title: 'Instagram Vanity Context',
      platform: 'instagram',
      type: 'image',
      src: '/images/solae/instagram/instagram-still-02.jpg',
      formatLabel: '4:5 Feed Portrait',
      aspectRatio: 'aspect-[4/5]',
      caption: 'Morning skincare routine arrangement pairing the serum with daily essentials.',
    },
    {
      id: 'solae-ig-s03',
      title: 'Instagram Texture Swatch',
      platform: 'instagram',
      type: 'image',
      src: '/images/solae/instagram/instagram-still-03.jpg',
      formatLabel: '4:5 Feed Portrait',
      aspectRatio: 'aspect-[4/5]',
      caption: 'Fingertip swatch showcasing crystal-clear transparency without white tint.',
    },
    {
      id: 'solae-ig-s04',
      title: 'Instagram Humidity Test Still',
      platform: 'instagram',
      type: 'image',
      src: '/images/solae/instagram/instagram-still-04.jpg',
      formatLabel: '4:5 Feed Portrait',
      aspectRatio: 'aspect-[4/5]',
      caption: 'Mist droplets beading cleanly off the bottle to symbolize humidity resistance.',
    },
    {
      id: 'solae-ig-story01',
      title: 'Instagram Vertical Story Still',
      platform: 'instagram',
      type: 'image',
      src: '/images/solae/instagram/instagram-story-01.jpg',
      formatLabel: '9:16 Fullscreen Story',
      aspectRatio: 'aspect-[9/16]',
      caption: 'Full-bleed vertical creative designed with tap-through zones for Instagram stories.',
    },
    {
      id: 'solae-ig-v01',
      title: 'Instagram Reel: Texture Bloom',
      platform: 'instagram',
      type: 'video',
      src: '/images/solae/instagram/instagram-video-01.mp4',
      formatLabel: '9:16 Vertical Reel',
      aspectRatio: 'aspect-[9/16]',
      caption: 'Sensory close-up of water serum spreading weightlessly across skin.',
    },
    {
      id: 'solae-ig-v02',
      title: 'Instagram Reel: 3-Second Absorb',
      platform: 'instagram',
      type: 'video',
      src: '/images/solae/instagram/instagram-video-02.mp4',
      formatLabel: '9:16 Vertical Reel',
      aspectRatio: 'aspect-[9/16]',
      caption: 'Real-time absorption test under warm daylight showing zero residue.',
    },
    {
      id: 'solae-ig-v03',
      title: 'Instagram Reel: Foundation Test',
      platform: 'instagram',
      type: 'video',
      src: '/images/solae/instagram/instagram-video-03.mp4',
      formatLabel: '9:16 Vertical Reel',
      aspectRatio: 'aspect-[9/16]',
      caption: 'Brush-buffed liquid foundation layered over the serum with complete adherence.',
    },
    {
      id: 'solae-ig-v04',
      title: 'Instagram Reel: UV Shield Visualizer',
      platform: 'instagram',
      type: 'video',
      src: '/images/solae/instagram/instagram-video-04.mp4',
      formatLabel: '9:16 Vertical Reel',
      aspectRatio: 'aspect-[9/16]',
      caption: 'Dynamic visual motion demonstrating full-spectrum protection against UV exposure.',
    },
  ],
}

export default function SolaePage() {
  return <CaseStudyTemplate data={SOLAE_DATA} />
}
