'use client'

import React from 'react'
import { CaseStudyTemplate, CaseStudyData } from '@/components/case-study-template'

const NUECERA_DATA: CaseStudyData = {
  campaignId: 'nuecera',
  caseNumber: '03',
  name: 'NUÉCERA',
  tagline: 'Moisturizing daily, but still dry? Restore & Strengthen the Barrier.',
  skuFocus: 'Moisturizing Cream · 16 OZ / 453 g (Full-Body & Face)',
  deliverablesCount: '35 Master Production Assets',
  channelsText: 'Meta · Instagram · TikTok · Website',
  heroImage: '/images/nuecera/meta/meta-product-01.jpg',
  heroCaption: 'Cylindrical white tub with signature eucalyptus ring accent and clinical typography.',
  heroBadge: 'Flagship Spec Commercial 03 · Witlyn Standard',
  brief: {
    whatItIs:
      'A dermatologist-developed, full-size (16 OZ / 453 g) daily barrier restoration moisturizing cream formulated for normal to dry, compromised skin. It penetrates deeply to seal micro-cracks and lock in moisture for 24 continuous hours.',
    whyItExists:
      'Many consumers experience tight, flaky, or stinging skin within 20 minutes of applying moisturizer because standard water-based lotions evaporate rapidly, while trendy 10-step routines over-layer harsh actives that strip the lipid barrier. Nuécera exists to deliver an uncomplicated, clinical barrier reset.',
    whyDifferent: [
      {
        title: '3 Essential Ceramides & Hyaluronic Acid',
        desc: 'Rebuilds the intercellular lipid matrix to halt trans-epidermal water loss and calm redness with zero fragrance sting.',
      },
      {
        title: 'Whipped Cloud Texture yet 100% Lightweight',
        desc: 'Holds dense, sculpted peaks like an ultra-rich cloud balm, yet instantly melts into a weightless, non-greasy velvet-matte finish.',
      },
    ],
    targetAudience:
      'Individuals suffering from flaky, compromised, or sensitized skin barriers, alongside corporate professionals battling drying office air-conditioning and tropical outdoor humidity.',
    packagingSpecs: {
      container:
        'Large, heavy cylindrical white tub with a flat-top white screw cap and a subtle sage-green/eucalyptus ring accent directly underneath the lid line.',
      labelTypography:
        'Nuécera | Developed with Dermatologists | Moisturizing Cream | For Normal to Dry Skin | Restores & Strengthens the Skin Barrier | With 3 Ceramides & Hyaluronic Acid | [Lightweight] | 16 OZ (453 g) | Dermatologist Tested',
    },
    marketAngles: [
      {
        title: 'United States Value Positioning',
        desc: '16 OZ full-body and facial volume anchored by clinical dermatologist authority, contrasting with tiny 1.7 oz luxury jars.',
      },
      {
        title: 'Southeast Asia Climate Defense',
        desc: 'Weightless barrier defense that seals skin from harsh corporate AC dryness without turning sticky in tropical heat.',
      },
    ],
  },
  strategy: {
    hooks: [
      {
        id: 1,
        angle: 'The Evaporation Paradox Hook',
        channelFit: 'Meta Feed & Paid Social Stills',
        quote: "Moisturizing daily, but still dry? It's about a stronger barrier.",
        rationale:
          'Addresses the common frustration where skin feels parched 20 minutes after moisturizing due to weak barrier lipid integrity.',
        commercialBenefit:
          'Disrupts habitual moisturizer repurchasing by reframing the core problem from hydration to lipid retention, driving higher initial conversion.',
      },
      {
        id: 2,
        angle: 'The 10-Step Fatigue Contrarian Angle',
        channelFit: 'TikTok Stills & Instagram Reels',
        quote: 'Stop destroying your skin with 10 steps.',
        rationale:
          'Appeals to consumers overwhelmed by multi-step regimens, offering a single dermatologist-tested tub that replaces elaborate layering routines.',
        commercialBenefit:
          'Positions Nuécera as the cost-effective hero SKU, increasing cart conversion among fatigued skincare buyers.',
      },
      {
        id: 3,
        angle: 'Whipped Cloud Weightless Proof',
        channelFit: 'Macro Video & Motion Reels',
        quote: 'Rich cloud hydration. Zero sticky residue.',
        rationale:
          'Proves visually that a heavy-duty ceramide cream can absorb completely matte without clogging pores or staining collars.',
        commercialBenefit:
          'Eliminates the top refund and bounce driver for rich creams (greasiness), boosting customer lifetime retention.',
      },
    ],
  },
  tabs: [
    { id: 'all', label: 'All Assets' },
    { id: 'meta', label: 'Meta Ads' },
    { id: 'instagram', label: 'Instagram' },
    { id: 'tiktok', label: 'TikTok' },
    { id: 'website', label: 'Website' },
  ],
  prevLink: {
    href: '/work/lipea',
    label: '02 LIPÉA Lip Serum',
  },
  nextLink: {
    href: '/work/aura-purify',
    label: '04 AURA PURIFY Cleanser',
  },
  assets: [
    // Meta Platform Assets (22)
    {
      id: 'meta-p1',
      title: 'Meta Product Hero',
      platform: 'meta',
      type: 'image',
      src: '/images/nuecera/meta/meta-product-01.jpg',
      formatLabel: '1:1 Square Feed Still',
      aspectRatio: 'aspect-square',
      caption: 'Studio hero packshot displaying the 16oz tub under balanced diffused lighting.',
    },
    {
      id: 'meta-p2',
      title: 'Meta Studio Still',
      platform: 'meta',
      type: 'image',
      src: '/images/nuecera/meta/meta-product-02.jpg',
      formatLabel: '1:1 Square Feed Still',
      aspectRatio: 'aspect-square',
      caption: 'Crisp angle emphasizing clean brand typography and the sage-green accent ring.',
    },
    {
      id: 'meta-p3',
      title: 'Meta Architectural Still',
      platform: 'meta',
      type: 'image',
      src: '/images/nuecera/meta/meta-product-03.jpg',
      formatLabel: '1:1 Square Feed Still',
      aspectRatio: 'aspect-square',
      caption: 'Architectural pedestal arrangement highlighting clinical dermatological authority.',
    },
    {
      id: 'meta-s1',
      title: 'Meta Feed Still 01',
      platform: 'meta',
      type: 'image',
      src: '/images/nuecera/meta/meta-still-01.jpg',
      formatLabel: '4:5 Feed Portrait',
      aspectRatio: 'aspect-[4/5]',
      caption: 'High-contrast feed portrait framed for maximum mobile screen engagement.',
    },
    {
      id: 'meta-s2',
      title: 'Meta Feed Still 02',
      platform: 'meta',
      type: 'image',
      src: '/images/nuecera/meta/meta-still-02.jpg',
      formatLabel: '4:5 Feed Portrait',
      aspectRatio: 'aspect-[4/5]',
      caption: 'Soft warm daylight capture showcasing generous volume and texture appeal.',
    },
    {
      id: 'meta-s3',
      title: 'Meta Feed Still 03',
      platform: 'meta',
      type: 'image',
      src: '/images/nuecera/meta/meta-still-03.jpg',
      formatLabel: '4:5 Feed Portrait',
      aspectRatio: 'aspect-[4/5]',
      caption: 'Detail view illustrating the smooth whipped cream texture inside the container.',
    },
    {
      id: 'meta-s4',
      title: 'Meta Feed Still 04',
      platform: 'meta',
      type: 'image',
      src: '/images/nuecera/meta/meta-still-04.jpg',
      formatLabel: '4:5 Feed Portrait',
      aspectRatio: 'aspect-[4/5]',
      caption: 'Minimalist staging emphasizing rapid 24-hour hydration benefits.',
    },
    {
      id: 'meta-o1',
      title: 'Meta Offer Variant 01',
      platform: 'meta',
      type: 'image',
      src: '/images/nuecera/meta/meta-offer-01.jpg',
      formatLabel: '1:1 Conversion Square',
      aspectRatio: 'aspect-square',
      caption: 'Direct-response offer visual optimized for paid retargeting ad campaigns.',
    },
    {
      id: 'meta-o2',
      title: 'Meta Offer Variant 02',
      platform: 'meta',
      type: 'image',
      src: '/images/nuecera/meta/meta-offer-02.jpg',
      formatLabel: '1:1 Conversion Square',
      aspectRatio: 'aspect-square',
      caption: 'Seasonal value bundle framing emphasizing long-term barrier maintenance.',
    },
    {
      id: 'meta-c1',
      title: 'Meta Creative Variant 01',
      platform: 'meta',
      type: 'image',
      src: '/images/nuecera/meta/meta-creative-01.jpg',
      formatLabel: '4:5 Creative Ad',
      aspectRatio: 'aspect-[4/5]',
      caption: 'High-contrast creative treatment testing barrier restoration headlines.',
    },
    {
      id: 'meta-c2',
      title: 'Meta Creative Variant 02',
      platform: 'meta',
      type: 'image',
      src: '/images/nuecera/meta/meta-creative-02.jpg',
      formatLabel: '4:5 Creative Ad',
      aspectRatio: 'aspect-[4/5]',
      caption: 'Editorial graphic layout focused on ceramide and hyaluronic acid actives.',
    },
    {
      id: 'meta-c3',
      title: 'Meta Creative Variant 03',
      platform: 'meta',
      type: 'image',
      src: '/images/nuecera/meta/meta-creative-03.jpg',
      formatLabel: '4:5 Creative Ad',
      aspectRatio: 'aspect-[4/5]',
      caption: 'Clinical comparison visual addressing continuous moisture barrier retention.',
    },
    {
      id: 'meta-c4',
      title: 'Meta Creative Variant 04',
      platform: 'meta',
      type: 'image',
      src: '/images/nuecera/meta/meta-creative-04.jpg',
      formatLabel: '4:5 Creative Ad',
      aspectRatio: 'aspect-[4/5]',
      caption: 'Lifestyle composition illustrating daily application for dry and sensitive skin.',
    },
    {
      id: 'meta-v1',
      title: 'Meta Motion Ad 01',
      platform: 'meta',
      type: 'video',
      src: '/images/nuecera/meta/meta-video-01.mp4',
      formatLabel: '9:16 Vertical Video',
      aspectRatio: 'aspect-[9/16]',
      caption: 'Sensory spatula swirl demonstrating rich whipped cloud texture.',
    },
    {
      id: 'meta-v2',
      title: 'Meta Motion Ad 02',
      platform: 'meta',
      type: 'video',
      src: '/images/nuecera/meta/meta-video-02.mp4',
      formatLabel: '9:16 Vertical Video',
      aspectRatio: 'aspect-[9/16]',
      caption: 'Fingertip melt demonstration showing fast absorption with zero grease.',
    },
    {
      id: 'meta-v3',
      title: 'Meta Motion Ad 03',
      platform: 'meta',
      type: 'video',
      src: '/images/nuecera/meta/meta-video-03.mp4',
      formatLabel: '9:16 Vertical Video',
      aspectRatio: 'aspect-[9/16]',
      caption: 'Skin barrier hydration test under controlled environmental conditions.',
    },
    {
      id: 'meta-v4',
      title: 'Meta Motion Ad 04',
      platform: 'meta',
      type: 'video',
      src: '/images/nuecera/meta/meta-video-04.mp4',
      formatLabel: '9:16 Vertical Video',
      aspectRatio: 'aspect-[9/16]',
      caption: 'Studio lighting pan highlighting smooth packaging and cap detail.',
    },
    {
      id: 'meta-v6',
      title: 'Meta Motion Ad 06',
      platform: 'meta',
      type: 'video',
      src: '/images/nuecera/meta/meta-video-06.mp4',
      formatLabel: '9:16 Vertical Video',
      aspectRatio: 'aspect-[9/16]',
      caption: 'Tactile cream dollop spreading cleanly across delicate facial skin.',
    },
    {
      id: 'meta-v7',
      title: 'Meta Motion Ad 07',
      platform: 'meta',
      type: 'video',
      src: '/images/nuecera/meta/meta-video-07.mp4',
      formatLabel: '9:16 Vertical Video',
      aspectRatio: 'aspect-[9/16]',
      caption: 'Rapid scroll-stopping visual showcasing the iconic white tub.',
    },
    {
      id: 'meta-v8',
      title: 'Meta Motion Ad 08',
      platform: 'meta',
      type: 'video',
      src: '/images/nuecera/meta/meta-video-08.mp4',
      formatLabel: '9:16 Vertical Video',
      aspectRatio: 'aspect-[9/16]',
      caption: 'Dynamic packaging rotation illustrating the 16oz high-volume value proposition.',
    },
    {
      id: 'meta-vg8',
      title: 'Meta Generative Video 08',
      platform: 'meta',
      type: 'video',
      src: '/images/nuecera/meta/meta-video-generation-08.mp4',
      formatLabel: '9:16 Generative Reel',
      aspectRatio: 'aspect-[9/16]',
      caption: 'Generative fluid animation simulating microscopic lipid barrier repair.',
    },
    {
      id: 'meta-vg10',
      title: 'Meta Generative Video 10',
      platform: 'meta',
      type: 'video',
      src: '/images/nuecera/meta/meta-video-generation-10.mp4',
      formatLabel: '9:16 Generative Reel',
      aspectRatio: 'aspect-[9/16]',
      caption: 'Optical particle visual demonstrating continuous moisture retention over time.',
    },

    // Instagram Suite (8)
    {
      id: 'ig-s1',
      title: 'Instagram Still 01',
      platform: 'instagram',
      type: 'image',
      src: '/images/nuecera/instagram/instagram-still-01.jpg',
      formatLabel: '4:5 Feed Portrait',
      aspectRatio: 'aspect-[4/5]',
      caption: 'Warm ambient capture styled for luxury aesthetic beauty grids.',
    },
    {
      id: 'ig-s2',
      title: 'Instagram Still 02',
      platform: 'instagram',
      type: 'image',
      src: '/images/nuecera/instagram/instagram-still-02.jpg',
      formatLabel: '4:5 Feed Portrait',
      aspectRatio: 'aspect-[4/5]',
      caption: 'Close-up texture swatch emphasizing the velvety whipped cloud finish.',
    },
    {
      id: 'ig-s3',
      title: 'Instagram Still 03',
      platform: 'instagram',
      type: 'image',
      src: '/images/nuecera/instagram/instagram-still-03.jpg',
      formatLabel: '4:5 Feed Portrait',
      aspectRatio: 'aspect-[4/5]',
      caption: 'Modern bathroom vanity placement highlighting daily ritual use.',
    },
    {
      id: 'ig-s4',
      title: 'Instagram Still 04',
      platform: 'instagram',
      type: 'image',
      src: '/images/nuecera/instagram/instagram-still-04.jpg',
      formatLabel: '4:5 Feed Portrait',
      aspectRatio: 'aspect-[4/5]',
      caption: 'Minimalist editorial composition focused on ingredient purity.',
    },
    {
      id: 'ig-c1',
      title: 'Instagram Creative Asset',
      platform: 'instagram',
      type: 'image',
      src: '/images/nuecera/instagram/instagram-creative-01.jpg',
      formatLabel: '4:5 Sponsored Ad',
      aspectRatio: 'aspect-[4/5]',
      caption: 'Sponsored feed ad framed around clinical dermatologist endorsements.',
    },
    {
      id: 'ig-story1',
      title: 'Instagram Story Asset',
      platform: 'instagram',
      type: 'image',
      src: '/images/nuecera/instagram/instagram-story-01.jpg',
      formatLabel: '9:16 Vertical Story',
      aspectRatio: 'aspect-[9/16]',
      caption: 'Vertical story asset with clear swipe-up link placement for direct sales.',
    },
    {
      id: 'ig-v1',
      title: 'Instagram Reel 01',
      platform: 'instagram',
      type: 'video',
      src: '/images/nuecera/instagram/instagram-video-01.mp4',
      formatLabel: '9:16 Vertical Reel',
      aspectRatio: 'aspect-[9/16]',
      caption: 'Sensory swirl and application reel tailored for organic discoverability.',
    },
    {
      id: 'ig-v2',
      title: 'Instagram Reel 02',
      platform: 'instagram',
      type: 'video',
      src: '/images/nuecera/instagram/instagram-video-02.mp4',
      formatLabel: '9:16 Vertical Reel',
      aspectRatio: 'aspect-[9/16]',
      caption: 'High-speed hydration test showing non-greasy absorption on dry skin.',
    },

    // TikTok Stills (4)
    {
      id: 'tt-s1',
      title: 'TikTok Format Still 01',
      platform: 'tiktok',
      type: 'image',
      src: '/images/nuecera/tiktok/tiktok-still-01.jpg',
      formatLabel: '9:16 Fullscreen Vertical',
      aspectRatio: 'aspect-[9/16]',
      caption: 'Full-bleed vertical still optimized for rapid algorithmic TikTok feeds.',
    },
    {
      id: 'tt-s2',
      title: 'TikTok Format Still 02',
      platform: 'tiktok',
      type: 'image',
      src: '/images/nuecera/tiktok/tiktok-still-02.jpg',
      formatLabel: '9:16 Fullscreen Vertical',
      aspectRatio: 'aspect-[9/16]',
      caption: 'Texture-focused vertical hook designed to spark curiosity in the first second.',
    },
    {
      id: 'tt-s3',
      title: 'TikTok Format Still 03',
      platform: 'tiktok',
      type: 'image',
      src: '/images/nuecera/tiktok/tiktok-still-03.jpg',
      formatLabel: '9:16 Fullscreen Vertical',
      aspectRatio: 'aspect-[9/16]',
      caption: 'Authentic creator-style setup showcasing the generous 453g tub size.',
    },
    {
      id: 'tt-s4',
      title: 'TikTok Format Still 04',
      platform: 'tiktok',
      type: 'image',
      src: '/images/nuecera/tiktok/tiktok-still-04.jpg',
      formatLabel: '9:16 Fullscreen Vertical',
      aspectRatio: 'aspect-[9/16]',
      caption: 'Direct comparison visual highlighting clinical barrier protection.',
    },

    // Website Still (1)
    {
      id: 'web-s1',
      title: 'Website E-Commerce Banner',
      platform: 'website',
      type: 'image',
      src: '/images/nuecera/website/website-still-01.jpg',
      formatLabel: '16:9 Landscape Banner',
      aspectRatio: 'aspect-[16/9]',
      caption: 'Hero landscape banner engineered for direct-to-consumer store landing pages.',
    },
  ],
}

export default function NueceraPage() {
  return <CaseStudyTemplate data={NUECERA_DATA} />
}
