'use client'

import React from 'react'
import { CaseStudyTemplate, CaseStudyData } from '@/components/case-study-template'

const AURA_PURIFY_DATA: CaseStudyData = {
  campaignId: 'aura-purify',
  caseNumber: '04',
  name: 'AURA PURIFY',
  tagline: 'Never Strip. Just Clean — Gel to Milk in 1 Second.',
  skuFocus: 'Barrier Gel-to-Milk Cleanser · 200 ml / 6.7 fl. oz.',
  deliverablesCount: '27 Master Production Assets',
  channelsText: 'Studio · Meta · Instagram',
  heroImage: '/images/aura-purify/studio/aura-product-01.jpg',
  heroCaption: 'Frosted amber apothecary glass bottle with matte black industrial pump on stone.',
  heroBadge: 'Flagship Spec Commercial 04 · Witlyn Standard',
  brief: {
    whatItIs:
      'A 200 ml (6.7 fl. oz.) restorative, phase-transforming daily facial cleanser and barrier defense treatment. It executes a seamless three-phase cleanse: Phase 1 (Dry Dissolve) melts waterproof SPF, long-wear foundation, and sebum without friction; Phase 2 (Water Emulsification) blossoms into a silky white milk in one second upon water contact; Phase 3 (Lipid-Safe Rinse) washes away completely without disrupting intercellular lipids.',
    whyItExists:
      'Traditional drugstore foaming cleansers rely on harsh sulfate detergents that strip vital stratum corneum lipids, causing the dreaded "tight plastic" post-wash sensation, persistent redness, and trans-epidermal dehydration. Simultaneously, daily sunscreen wearers suffer from double-cleanse fatigue—juggling separate cleansing oils and foamy face washes.',
    whyDifferent: [
      {
        title: '50% Plant-Glycerin + Oat Kernel Base',
        desc: 'While ordinary cleansers contain 70–80% filler water, AURA PURIFY is formulated with a 50% plant-derived glycerin, oat kernel extract, and barrier lipid foundation with a rich honey-like cushion.',
      },
      {
        title: 'Optical Phase-Shift & 2-in-1 Utility',
        desc: 'Replaces the cumbersome two-step double cleanse in a single rinse, creating an unmistakable scroll-stopping visual as amber gel transforms instantly into velvet milk on camera.',
      },
    ],
    targetAudience:
      'Urban individuals (ages 20–35) dealing with sensitive, acid-compromised, or dry skin barriers, and daily wearers of waterproof SPF and long-wear makeup looking for a gentle one-step ritual.',
    packagingSpecs: {
      container:
        'Heavy-base, vertically elongated 200ml cylindrical frosted amber apothecary glass bottle crowned with a low-profile matte black industrial pump.',
      labelTypography:
        'AURA | PURIFY | BARRIER GEL-TO-MILK CLEANSER | 50% Plant Glycerin • Oat Kernel • Lipids | 200 ml / 6.7 fl. oz. (printed on tactile uncoated matte cream paper)',
    },
    marketAngles: [
      {
        title: 'Anti-Strip Cleanser Education',
        desc: '"Squeaky-clean skin isn\'t healthy—it’s damaged" — calling out the false belief that tight, squeaky skin equals clean pores.',
      },
      {
        title: 'Sensory Transformation Proof',
        desc: '"Gel to Milk in 1 Second" — high-speed macro videography documenting the instant kinetic emulsification upon water contact.',
      },
    ],
  },
  strategy: {
    hooks: [
      {
        id: 1,
        angle: 'The Squeaky-Clean Misconception',
        channelFit: 'Meta 4:5 Feed & Instagram Reels',
        quote: "Squeaky-clean skin isn't healthy—it’s damaged.",
        whyChosen:
          'Consumers are conditioned to associate skin squeakiness with purity, even though it signals severe lipid-barrier destruction. Subverting this misconception instantly polarizes attention and positions the brand as a dermatological ally.',
        rationale:
          'Dismantles the cultural conditioning that cleansers should leave skin feeling tight, educating consumers that squeakiness is the feeling of stripped lipids.',
        projectedRoas: '4.4x – 5.0x Target ROAS',
        thumbStopRate: '45%+ (3s View)',
        cpaImpact: '-35% Lower CPA',
        commercialBenefit:
          'Drives category re-education, unlocking skeptical shoppers who avoid foaming cleansers and establishing premium scientific authority.',
        expectedOutcome: 'Positions AURA PURIFY as the daily non-stripping cleanser for chronic barrier redness, driving repeat orders every 45 days.',
      },
      {
        id: 2,
        angle: 'The 1-Second Optical Phase Shift',
        channelFit: 'Paid Video Reels & Stories',
        quote: 'Gel to Milk in 1 Second.',
        whyChosen:
          'In social feeds, visual transformation consistently outperforms static product claims. The golden translucent gel blooming into rich white milk delivers immediate thumb-stopping tactile satisfaction.',
        rationale:
          'Leverages the visual appeal of golden translucent gel blooming into rich white milk the exact millisecond water touches the face.',
        projectedRoas: '4.6x – 5.2x Target ROAS',
        thumbStopRate: '51%+ (3s View)',
        cpaImpact: '-39% Lower CPA',
        commercialBenefit:
          'Delivers an instant 1.2-second thumb-stop on paid feeds, lowering CPA by up to 34% through sensory transformation proof.',
        expectedOutcome: 'Generates rapid direct-to-cart clicks from viewers intrigued by the real-time emulsification proof.',
      },
      {
        id: 3,
        angle: 'Double-Cleanse Fatigue Solution',
        channelFit: 'Meta Carousels & Conversion Ads',
        quote: 'Never Strip. Just Clean.',
        whyChosen:
          'Modern skincare buyers are tired of buying both an oil balm and a foaming cleanser. Consolidating two steps into a single 200ml ritual dramatically lowers buying friction.',
        rationale:
          'Positions AURA PURIFY as the definitive single-step answer that melts waterproof makeup and cleanses pores without requiring two separate products.',
        projectedRoas: '4.1x – 4.7x Target ROAS',
        thumbStopRate: '42%+ (3s View)',
        cpaImpact: '-30% Blended CPA',
        commercialBenefit:
          'Simplifies buying friction by consolidating two expensive SKUs into one daily luxury ritual, boosting AOV and repeat rate.',
        expectedOutcome: 'High customer lifetime value (LTV) due to daily ritual habituation and bathroom vanity essentiality.',
      },
    ],
  },
  tabs: [
    { id: 'all', label: 'All Assets' },
    { id: 'studio', label: 'Studio Master Stills' },
    { id: 'meta', label: 'Meta Ads' },
    { id: 'instagram', label: 'Instagram Suite' },
  ],
  prevLink: {
    href: '/work/nuecera',
    label: '03 NUÉCERA Moisturizer',
  },
  nextLink: {
    href: '/work/vyraa',
    label: '05 VYRAA Neck Complex',
  },
  assets: [
    // Studio Master Captures (7)
    {
      id: 'aura-std-01',
      title: 'Amber Bottle Studio Anchor',
      platform: 'studio',
      type: 'image',
      src: '/images/aura-purify/studio/aura-product-01.jpg',
      formatLabel: 'Master Studio Capture · 4:5',
      aspectRatio: 'aspect-[4/5]',
      caption: 'Frosted amber apothecary glass bottle resting on a chiseled stone pedestal.',
    },
    {
      id: 'aura-std-02',
      title: 'Golden Honey Gel Viscosity',
      platform: 'studio',
      type: 'image',
      src: '/images/aura-purify/studio/aura-product-02.jpg',
      formatLabel: 'Macro Texture · 4:5',
      aspectRatio: 'aspect-[4/5]',
      caption: 'Dense honey-thick glycerin gel bead showing rich amber translucency.',
    },
    {
      id: 'aura-std-03',
      title: 'Water Contact Phase Shift',
      platform: 'studio',
      type: 'image',
      src: '/images/aura-purify/studio/aura-product-03.jpg',
      formatLabel: 'Emulsification Still · 4:5',
      aspectRatio: 'aspect-[4/5]',
      caption: 'Initial water droplet contact blooming the golden gel into silky white milk.',
    },
    {
      id: 'aura-std-04',
      title: 'Matte Industrial Pump Macro',
      platform: 'studio',
      type: 'image',
      src: '/images/aura-purify/studio/aura-product-04.jpg',
      formatLabel: 'Hardware Still · 4:5',
      aspectRatio: 'aspect-[4/5]',
      caption: 'Low-profile matte black pump designed for controlled and hygienic dispensing.',
    },
    {
      id: 'aura-std-05',
      title: 'Uncoated Limestone Label Detail',
      platform: 'studio',
      type: 'image',
      src: '/images/aura-purify/studio/aura-product-05.jpg',
      formatLabel: 'Packaging Macro · 4:5',
      aspectRatio: 'aspect-[4/5]',
      caption: 'Tactile cream paper label highlighting clean architectural ingredient typography.',
    },
    {
      id: 'aura-std-06',
      title: 'Lipid-Safe Surface Rinse Still',
      platform: 'studio',
      type: 'image',
      src: '/images/aura-purify/studio/aura-product-06.jpg',
      formatLabel: 'Cleanse Finish · 4:5',
      aspectRatio: 'aspect-[4/5]',
      caption: 'Clear water sheeting cleanly off skin leaving natural barrier moisture intact.',
    },

    // Meta Platform Assets (11)
    {
      id: 'aura-meta-s01',
      title: 'Meta Hero Feed Still',
      platform: 'meta',
      type: 'image',
      src: '/images/aura-purify/meta/meta-still-01.jpg',
      formatLabel: '1:1 Square Feed',
      aspectRatio: 'aspect-square',
      caption: 'High-contrast square hero packshot designed for high click-through ad campaigns.',
    },
    {
      id: 'aura-meta-s01var',
      title: 'Meta Variant Feed Still 01',
      platform: 'meta',
      type: 'image',
      src: '/images/aura-purify/meta/meta-still-01-var.jpg',
      formatLabel: '1:1 Square Feed',
      aspectRatio: 'aspect-square',
      caption: 'Warm amber lighting variation emphasizing the soothing plant-glycerin base.',
    },
    {
      id: 'aura-meta-s02',
      title: 'Meta Feed Portrait Still 02',
      platform: 'meta',
      type: 'image',
      src: '/images/aura-purify/meta/meta-still-02.jpg',
      formatLabel: '4:5 Feed Portrait',
      aspectRatio: 'aspect-[4/5]',
      caption: 'Vertical composition contrasting foaming cleanser tightness with gentle milk hydration.',
    },
    {
      id: 'aura-meta-s02var',
      title: 'Meta Variant Feed Still 02',
      platform: 'meta',
      type: 'image',
      src: '/images/aura-purify/meta/meta-still-02-var.jpg',
      formatLabel: '4:5 Feed Portrait',
      aspectRatio: 'aspect-[4/5]',
      caption: 'Close framing highlighting the 200ml apothecary bottle on wet slate.',
    },
    {
      id: 'aura-meta-s03',
      title: 'Meta Makeup Dissolve Still 03',
      platform: 'meta',
      type: 'image',
      src: '/images/aura-purify/meta/meta-still-03.jpg',
      formatLabel: '4:5 Feed Portrait',
      aspectRatio: 'aspect-[4/5]',
      caption: 'Macro demonstration melting waterproof sunscreen and foundation effortlessly.',
    },
    {
      id: 'aura-meta-s03var',
      title: 'Meta Variant Feed Still 03',
      platform: 'meta',
      type: 'image',
      src: '/images/aura-purify/meta/meta-still-03-var.jpg',
      formatLabel: '4:5 Feed Portrait',
      aspectRatio: 'aspect-[4/5]',
      caption: 'Direct-response visual proving quick emulsification with zero oily film.',
    },
    {
      id: 'aura-meta-v02',
      title: 'Meta Motion Reel: SPF & Waterproof Dissolve',
      platform: 'meta',
      type: 'video',
      src: '/images/aura-purify/meta/meta-video-02.mp4',
      formatLabel: '9:16 Vertical Video',
      aspectRatio: 'aspect-[9/16]',
      caption: 'Waterproof makeup and mineral sunscreen melting cleanly under dry gel friction.',
    },
    {
      id: 'aura-meta-v01',
      title: 'Meta Motion Reel: Gel-to-Milk Blooming',
      platform: 'meta',
      type: 'video',
      src: '/images/aura-purify/meta/meta-video-01.mp4',
      formatLabel: '9:16 Vertical Video',
      aspectRatio: 'aspect-[9/16]',
      caption: 'One-second optical transformation from thick amber gel to creamy white milk.',
    },
    {
      id: 'aura-meta-v03',
      title: 'Meta Motion Reel: Zero-Tightness Rinse',
      platform: 'meta',
      type: 'video',
      src: '/images/aura-purify/meta/meta-video-03.mp4',
      formatLabel: '9:16 Vertical Video',
      aspectRatio: 'aspect-[9/16]',
      caption: 'Post-rinse skin test proving complete cleanliness with zero stripped tightness.',
    },
    {
      id: 'aura-meta-v04',
      title: 'Meta Motion Reel: 50% Glycerin Cushion',
      platform: 'meta',
      type: 'video',
      src: '/images/aura-purify/meta/meta-video-04.mp4',
      formatLabel: '9:16 Vertical Video',
      aspectRatio: 'aspect-[9/16]',
      caption: 'Tactile gel stretch demonstrating high humectant viscosity and skin glide.',
    },
    {
      id: 'aura-meta-v05',
      title: 'Meta Motion Reel: One-Step Double Cleanse',
      platform: 'meta',
      type: 'video',
      src: '/images/aura-purify/meta/meta-video-05.mp4',
      formatLabel: '9:16 Vertical Video',
      aspectRatio: 'aspect-[9/16]',
      caption: 'Split comparison replacing two separate cleansers with a single bottle.',
    },

    // Instagram Suite (9)
    {
      id: 'aura-ig-s01',
      title: 'Instagram Botanical Vanity Still',
      platform: 'instagram',
      type: 'image',
      src: '/images/aura-purify/instagram/instagram-still-01.jpg',
      formatLabel: '4:5 Feed Portrait',
      aspectRatio: 'aspect-[4/5]',
      caption: 'Aesthetic bathroom vanity setting highlighting natural oat and amber tones.',
    },
    {
      id: 'aura-ig-s02',
      title: 'Instagram Gel Ribbon Texture',
      platform: 'instagram',
      type: 'image',
      src: '/images/aura-purify/instagram/instagram-still-02.jpg',
      formatLabel: '4:5 Feed Portrait',
      aspectRatio: 'aspect-[4/5]',
      caption: 'Ribbon swatch of dense amber gel displaying smooth non-drip cohesion.',
    },
    {
      id: 'aura-ig-s03',
      title: 'Instagram Milky Emulsion Still',
      platform: 'instagram',
      type: 'image',
      src: '/images/aura-purify/instagram/instagram-still-03.jpg',
      formatLabel: '4:5 Feed Portrait',
      aspectRatio: 'aspect-[4/5]',
      caption: 'Velvety milk droplets cascading over glass to showcase ultra-gentle rinsing.',
    },
    {
      id: 'aura-ig-story01',
      title: 'Instagram Story Creative 01',
      platform: 'instagram',
      type: 'image',
      src: '/images/aura-purify/instagram/instagram-story-01.jpg',
      formatLabel: '9:16 Vertical Story',
      aspectRatio: 'aspect-[9/16]',
      caption: 'Story card highlighting three-phase transformation for link-click campaigns.',
    },
    {
      id: 'aura-ig-story02',
      title: 'Instagram Story Creative 02',
      platform: 'instagram',
      type: 'image',
      src: '/images/aura-purify/instagram/instagram-story-02.jpg',
      formatLabel: '9:16 Vertical Story',
      aspectRatio: 'aspect-[9/16]',
      caption: 'Interactive story quiz graphic addressing common post-cleanse barrier damage.',
    },
    {
      id: 'aura-ig-v01',
      title: 'Instagram Reel: Dry-to-Wet Ritual',
      platform: 'instagram',
      type: 'video',
      src: '/images/aura-purify/instagram/instagram-video-01.mp4',
      formatLabel: '9:16 Vertical Reel',
      aspectRatio: 'aspect-[9/16]',
      caption: 'Calming step-by-step evening cleanse ritual demonstrating effortless makeup removal.',
    },
    {
      id: 'aura-ig-v02',
      title: 'Instagram Reel: Micro-Emulsion Burst',
      platform: 'instagram',
      type: 'video',
      src: '/images/aura-purify/instagram/instagram-video-02.mp4',
      formatLabel: '9:16 Vertical Reel',
      aspectRatio: 'aspect-[9/16]',
      caption: 'Slow-motion splash capturing instant milk formation on skin surface.',
    },
    {
      id: 'aura-ig-v03',
      title: 'Instagram Reel: The Lipid Barrier Shield',
      platform: 'instagram',
      type: 'video',
      src: '/images/aura-purify/instagram/instagram-video-03.mp4',
      formatLabel: '9:16 Vertical Reel',
      aspectRatio: 'aspect-[9/16]',
      caption: 'Educational visual explaining how plant-glycerin guards against skin dehydration.',
    },
    {
      id: 'aura-ig-v04',
      title: 'Instagram Reel: Single-Rinse Speed',
      platform: 'instagram',
      type: 'video',
      src: '/images/aura-purify/instagram/instagram-video-04.mp4',
      formatLabel: '9:16 Vertical Reel',
      aspectRatio: 'aspect-[9/16]',
      caption: 'Rapid cleanse test proving complete mascara and sunscreen removal in thirty seconds.',
    },
  ],
}

export default function AuraPurifyPage() {
  return <CaseStudyTemplate data={AURA_PURIFY_DATA} />
}
